name: CMake Build and Test with Coverage

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean old build and coverage files
      run: |
        rm -rf _build
        find . -name '*.gcda' -o -name '*.gcno' | xargs -r rm -f

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: Configure CMake
      run: cmake -S . -B _build -DBUILD_TESTS=ON

    - name: Build project
      run: cmake --build _build -- -j

    - name: Run tests
      run: |
        cd _build
        ctest --verbose

    - name: Capture coverage info
      run: |
        cd _build
        # Захватываем покрытие, игнорируем предупреждения inconsistent
        lcov --capture --directory . --output-file coverage.info --ignore-errors inconsistent,unused
        lcov --remove coverage.info '/usr/*' --output-file coverage.info --ignore-errors unused
        lcov --list coverage.info

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: _build/coverage.info

