name: CMake Build and Test with Coverage

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: Configure CMake
      run: cmake -S . -B _build -DBUILD_TESTS=ON

    - name: Build project
      run: cmake --build _build -- -j

    - name: Run tests
      run: |
        cd _build
        ctest --verbose

    - name: Capture coverage info
      run: |
        cd _build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' 'third-party/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: _build/coverage.info
    - name: Init submodules
      run: git submodule update --init --recursive
    - name: Capture coverage info
      run: |
        cd _build
        geninfo . --output-filename coverage.info --memory 0 --rc geninfo_unexecuted_blocks=1 --rc geninfo_ignore_errors=mismatch
